package io.github.jasper.mybatis.encrypt.core.mask;

import io.github.jasper.mybatis.encrypt.algorithm.AlgorithmRegistry;
import io.github.jasper.mybatis.encrypt.annotation.SensitiveField;
import io.github.jasper.mybatis.encrypt.core.metadata.EncryptColumnRule;
import io.github.jasper.mybatis.encrypt.exception.EncryptionConfigurationException;
import io.github.jasper.mybatis.encrypt.exception.EncryptionErrorCode;
import io.github.jasper.mybatis.encrypt.util.ObjectTraversalUtils;
import io.github.jasper.mybatis.encrypt.util.PropertyValueAccessor;
import io.github.jasper.mybatis.encrypt.util.StringUtils;

import java.lang.reflect.Array;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

/**
 * Applies controller-boundary masking to response objects.
 *
 * <p>This component is deliberately placed after MyBatis result decryption and before HTTP message
 * conversion. It never decides whether a controller is allowed to return sensitive data; that
 * decision is represented by the active {@link SensitiveDataContext}. When masking is required,
 * recorded decrypted references are processed first so the replacement targets the exact DTO
 * instances returned by the controller.</p>
 *
 * <p>Replacement order for recorded values is:</p>
 * <ol>
 *     <li>stored masked values resolved from {@link StoredSensitiveValueResolver};</li>
 *     <li>fallback value generated by the field rule's effective masked algorithm;</li>
 *     <li>{@link SensitiveField} masking on the recorded field, when present.</li>
 * </ol>
 *
 * <p>{@link SensitiveField} supports three annotation-level masking modes. A custom
 * {@link SensitiveFieldMasker} bean has the highest priority, a referenced LIKE algorithm is next,
 * and the built-in type based mask is the default fallback.</p>
 *
 * <p>The class is thread-safe. Annotation bindings are cached by response class, while request
 * state is read only from {@link SensitiveDataContext}.</p>
 */
public final class SensitiveDataMasker {

    private final StoredSensitiveValueResolver storedSensitiveValueResolver;
    private final AlgorithmRegistry algorithmRegistry;
    private final Map<String, SensitiveFieldMasker> sensitiveFieldMaskers;
    private final PropertyValueAccessor propertyValueAccessor = new PropertyValueAccessor();
    private final ConcurrentMap<Class<?>, List<FieldBinding>> fieldBindings =
            new ConcurrentHashMap<Class<?>, List<FieldBinding>>();

    /**
     * Creates a masker without stored-value resolution support.
     *
     * <p>With this constructor, recorded encrypted fields can still be masked by
     * {@code maskedAlgorithm} fallback or by {@link SensitiveField}; database stored masked values
     * are simply skipped.</p>
     */
    public SensitiveDataMasker() {
        this(null, null);
    }

    /**
     * Creates a masker with optional stored-value resolution support.
     *
     * @param storedSensitiveValueResolver stored masked value resolver, may be {@code null}
     * @param algorithmRegistry algorithm registry used for fallback masking
     */
    public SensitiveDataMasker(StoredSensitiveValueResolver storedSensitiveValueResolver,
                               AlgorithmRegistry algorithmRegistry) {
        this(storedSensitiveValueResolver, algorithmRegistry, null);
    }

    /**
     * Creates a masker with optional stored-value, LIKE algorithm and custom field-masker support.
     *
     * @param storedSensitiveValueResolver stored masked value resolver, may be {@code null}
     * @param algorithmRegistry algorithm registry used for fallback masking
     * @param sensitiveFieldMaskers custom response field maskers keyed by bean name
     */
    public SensitiveDataMasker(StoredSensitiveValueResolver storedSensitiveValueResolver,
                               AlgorithmRegistry algorithmRegistry,
                               Map<String, SensitiveFieldMasker> sensitiveFieldMaskers) {
        this.storedSensitiveValueResolver = storedSensitiveValueResolver;
        this.algorithmRegistry = algorithmRegistry;
        this.sensitiveFieldMaskers = sensitiveFieldMaskers == null
                ? Collections.<String, SensitiveFieldMasker>emptyMap()
                : Collections.unmodifiableMap(new LinkedHashMap<String, SensitiveFieldMasker>(sensitiveFieldMaskers));
    }

    /**
     * Masks the response object according to the active {@link SensitiveDataContext}.
     *
     * <p>The method mutates the supplied object graph in place and returns the same object
     * reference. If no masking scope is active, the object is returned unchanged.</p>
     *
     * @param body controller response body
     * @return original response body reference
     */
    public Object mask(Object body) {
        if (body == null || !SensitiveDataContext.shouldMask()) {
            return body;
        }
        SensitiveResponseStrategy strategy = SensitiveDataContext.strategy();
        if (strategy == SensitiveResponseStrategy.RECORDED_ONLY
                || strategy == SensitiveResponseStrategy.RECORDED_THEN_ANNOTATED) {
            maskRecordedReferences();
        }
        if (strategy == SensitiveResponseStrategy.ANNOTATED_FIELDS
                || strategy == SensitiveResponseStrategy.RECORDED_THEN_ANNOTATED) {
            maskAnnotatedObjectGraph(body);
        }
        return body;
    }

    /**
     * Masks only currently recorded decrypted references.
     *
     * <p>This path is the preferred strategy for normal MyBatis query responses because it avoids
     * traversing the full response graph and replaces only fields that were actually decrypted by
     * the plugin.</p>
     */
    public void maskRecordedReferences() {
        Collection<SensitiveDataContext.SensitiveRecord> records = SensitiveDataContext.records();
        Map<SensitiveDataContext.SensitiveRecord, String> resolvedStoredValues =
                storedSensitiveValueResolver == null
                        ? Collections.<SensitiveDataContext.SensitiveRecord, String>emptyMap()
                        : storedSensitiveValueResolver.resolve(records);
        for (SensitiveDataContext.SensitiveRecord record : records) {
            String storedMaskedValue = resolvedStoredValues.get(record);
            if (StringUtils.isNotBlank(storedMaskedValue) && applyRecordedValue(record, storedMaskedValue)) {
                continue;
            }
            EncryptColumnRule rule = record.rule();
            if (rule != null && rule.hasMaskedColumn() && algorithmRegistry != null) {
                String fallbackMaskedValue = algorithmRegistry.like(rule.effectiveMaskedAlgorithm()).transform(record.value());
                if (applyRecordedValue(record, fallbackMaskedValue)) {
                    continue;
                }
            }
            FieldBinding binding = binding(record.owner().getClass(), record.propertyName()).orElse(null);
            if (binding != null) {
                binding.setMasked(record.owner(), record.value(), algorithmRegistry, sensitiveFieldMaskers);
            }
        }
    }

    /**
     * Traverses a returned object graph and masks annotated {@link SensitiveField} String fields.
     *
     * <p>This strategy is intended for manually assembled DTOs that were not recorded by
     * {@link SensitiveDataContext}. Object identity tracking prevents infinite recursion for cyclic
     * graphs.</p>
     *
     * @param body response body
     */
    public void maskAnnotatedObjectGraph(Object body) {
        IdentityHashMap<Object, Boolean> visited = new IdentityHashMap<Object, Boolean>();
        maskObject(body, visited);
    }

    private void maskObject(Object value, IdentityHashMap<Object, Boolean> visited) {
        if (value == null || ObjectTraversalUtils.isSimpleValueType(value.getClass())) {
            return;
        }
        if (visited.put(value, Boolean.TRUE) != null) {
            return;
        }
        Class<?> type = value.getClass();
        if (type.isArray()) {
            int length = Array.getLength(value);
            for (int index = 0; index < length; index++) {
                maskObject(Array.get(value, index), visited);
            }
            return;
        }
        if (value instanceof Iterable<?>) {
            for (Object item : (Iterable<?>) value) {
                maskObject(item, visited);
            }
            return;
        }
        if (value instanceof Map<?, ?>) {
            for (Object item : ((Map<?, ?>) value).values()) {
                maskObject(item, visited);
            }
            return;
        }
        if (type.getName().startsWith("java.")) {
            return;
        }
        for (FieldBinding binding : bindings(type)) {
            binding.maskCurrentValue(value, algorithmRegistry, sensitiveFieldMaskers);
        }
        for (Field field : allFields(type)) {
            if (Modifier.isStatic(field.getModifiers()) || field.getAnnotation(SensitiveField.class) != null) {
                continue;
            }
            if (ObjectTraversalUtils.isSimpleValueType(field.getType())) {
                continue;
            }
            try {
                field.setAccessible(true);
                maskObject(field.get(value), visited);
            } catch (IllegalAccessException ignore) {
                // Best-effort traversal; inaccessible non-sensitive fields do not block response masking.
            }
        }
    }

    private Optional<FieldBinding> binding(Class<?> type, String propertyName) {
        for (FieldBinding binding : bindings(type)) {
            if (binding.field.getName().equals(propertyName)) {
                return Optional.of(binding);
            }
        }
        return Optional.empty();
    }

    private boolean applyRecordedValue(SensitiveDataContext.SensitiveRecord record, String replacement) {
        if (StringUtils.isBlank(replacement)) {
            return false;
        }
        PropertyValueAccessor.PropertyReference propertyReference =
                propertyValueAccessor.resolve(record.owner(), record.propertyName());
        if (propertyReference == null || !propertyReference.canWrite()) {
            return false;
        }
        Object currentValue = propertyReference.getValue();
        return (currentValue == null || currentValue instanceof String) && propertyReference.setValue(replacement);
    }

    private List<FieldBinding> bindings(Class<?> type) {
        List<FieldBinding> cached = fieldBindings.get(type);
        if (cached != null) {
            return cached;
        }
        List<FieldBinding> resolved = resolveBindings(type);
        List<FieldBinding> previous = fieldBindings.putIfAbsent(type, resolved);
        return previous == null ? resolved : previous;
    }

    private List<FieldBinding> resolveBindings(Class<?> type) {
        List<FieldBinding> bindings = new ArrayList<FieldBinding>();
        for (Field field : allFields(type)) {
            SensitiveField annotation = field.getAnnotation(SensitiveField.class);
            if (annotation == null) {
                continue;
            }
            if (!String.class.equals(field.getType())) {
                throw new EncryptionConfigurationException(EncryptionErrorCode.INVALID_FIELD_RULE,
                        "@SensitiveField can only be used on String fields: "
                                + field.getDeclaringClass().getName() + "." + field.getName());
            }
            if (Modifier.isStatic(field.getModifiers()) || Modifier.isFinal(field.getModifiers())) {
                throw new EncryptionConfigurationException(EncryptionErrorCode.INVALID_FIELD_RULE,
                        "@SensitiveField cannot be used on static or final fields: "
                                + field.getDeclaringClass().getName() + "." + field.getName());
            }
            field.setAccessible(true);
            bindings.add(new FieldBinding(field, annotation, parseOptions(annotation, field)));
        }
        return Collections.unmodifiableList(bindings);
    }

    private Map<String, String> parseOptions(SensitiveField annotation, Field field) {
        String[] options = annotation.options();
        if (options == null || options.length == 0) {
            return Collections.emptyMap();
        }
        Map<String, String> parsed = new LinkedHashMap<String, String>();
        for (String option : options) {
            if (StringUtils.isBlank(option)) {
                continue;
            }
            int splitIndex = option.indexOf('=');
            if (splitIndex <= 0) {
                throw new EncryptionConfigurationException(EncryptionErrorCode.INVALID_FIELD_RULE,
                        "@SensitiveField options must use key=value: "
                                + field.getDeclaringClass().getName() + "." + field.getName()
                                + ", option=" + option);
            }
            String key = option.substring(0, splitIndex).trim();
            if (StringUtils.isBlank(key)) {
                throw new EncryptionConfigurationException(EncryptionErrorCode.INVALID_FIELD_RULE,
                        "@SensitiveField option key must not be blank: "
                                + field.getDeclaringClass().getName() + "." + field.getName()
                                + ", option=" + option);
            }
            if (parsed.containsKey(key)) {
                throw new EncryptionConfigurationException(EncryptionErrorCode.INVALID_FIELD_RULE,
                        "@SensitiveField option key is duplicated: "
                                + field.getDeclaringClass().getName() + "." + field.getName()
                                + ", key=" + key);
            }
            parsed.put(key, option.substring(splitIndex + 1).trim());
        }
        return Collections.unmodifiableMap(parsed);
    }

    private List<Field> allFields(Class<?> type) {
        if (type == null || type == Object.class) {
            return Collections.emptyList();
        }
        List<Field> fields = new ArrayList<Field>();
        Class<?> current = type;
        while (current != null && current != Object.class) {
            Collections.addAll(fields, current.getDeclaredFields());
            current = current.getSuperclass();
        }
        return fields;
    }

    private static final class FieldBinding {

        private final Field field;
        private final SensitiveField annotation;
        private final Map<String, String> options;

        private FieldBinding(Field field, SensitiveField annotation, Map<String, String> options) {
            this.field = field;
            this.annotation = annotation;
            this.options = options;
        }

        private void maskCurrentValue(Object owner,
                                      AlgorithmRegistry algorithmRegistry,
                                      Map<String, SensitiveFieldMasker> sensitiveFieldMaskers) {
            try {
                Object value = field.get(owner);
                if (value instanceof String) {
                    field.set(owner, mask(owner, (String) value, algorithmRegistry, sensitiveFieldMaskers));
                }
            } catch (IllegalAccessException ignore) {
                // Field accessibility was prepared when binding was built.
            }
        }

        private void setMasked(Object owner,
                               String value,
                               AlgorithmRegistry algorithmRegistry,
                               Map<String, SensitiveFieldMasker> sensitiveFieldMaskers) {
            try {
                field.set(owner, mask(owner, value, algorithmRegistry, sensitiveFieldMaskers));
            } catch (IllegalAccessException ignore) {
                // Field accessibility was prepared when binding was built.
            }
        }

        private String mask(Object owner,
                            String value,
                            AlgorithmRegistry algorithmRegistry,
                            Map<String, SensitiveFieldMasker> sensitiveFieldMaskers) {
            if (StringUtils.isBlank(value)) {
                return value;
            }
            if (StringUtils.isNotBlank(annotation.masker())) {
                SensitiveFieldMasker masker = sensitiveFieldMaskers.get(annotation.masker());
                if (masker == null) {
                    throw new EncryptionConfigurationException(EncryptionErrorCode.MISSING_SENSITIVE_FIELD_MASKER,
                            "Missing sensitive field masker bean: " + annotation.masker()
                                    + " for " + field.getDeclaringClass().getName() + "." + field.getName());
                }
                String masked = masker.mask(value, new SensitiveFieldMaskingContext(
                        owner, field.getDeclaringClass(), field.getName(), annotation, options));
                return masked == null ? value : masked;
            }
            if (StringUtils.isNotBlank(annotation.likeAlgorithm())) {
                if (algorithmRegistry == null) {
                    throw new EncryptionConfigurationException(EncryptionErrorCode.MISSING_LIKE_QUERY_ALGORITHM,
                            "Missing AlgorithmRegistry for @SensitiveField likeAlgorithm: "
                                    + annotation.likeAlgorithm() + " on "
                                    + field.getDeclaringClass().getName() + "." + field.getName());
                }
                return algorithmRegistry.like(annotation.likeAlgorithm()).transform(value);
            }
            SensitiveMaskType type = resolveType();
            if (type == SensitiveMaskType.EMAIL) {
                return maskEmail(value, annotation.maskChar());
            }
            int keepFirst = annotation.keepFirst() >= 0 ? annotation.keepFirst() : defaultKeepFirst(type);
            int keepLast = annotation.keepLast() >= 0 ? annotation.keepLast() : defaultKeepLast(type);
            return maskRange(value, keepFirst, keepLast, annotation.maskChar());
        }

        private SensitiveMaskType resolveType() {
            if (annotation.type() != SensitiveMaskType.AUTO) {
                return annotation.type();
            }
            String name = field.getName().toLowerCase(Locale.ROOT);
            if (name.contains("phone") || name.contains("mobile") || name.contains("tel")) {
                return SensitiveMaskType.PHONE;
            }
            if (name.contains("idcard") || name.contains("id_card") || name.contains("credential")
                    || name.contains("cert")) {
                return SensitiveMaskType.ID_CARD;
            }
            if (name.contains("bank") || name.contains("card")) {
                return SensitiveMaskType.BANK_CARD;
            }
            if (name.contains("email") || name.contains("mail")) {
                return SensitiveMaskType.EMAIL;
            }
            if (name.contains("name")) {
                return SensitiveMaskType.NAME;
            }
            return SensitiveMaskType.DEFAULT;
        }

        private int defaultKeepFirst(SensitiveMaskType type) {
            switch (type) {
                case ID_CARD:
                    return 3;
                case BANK_CARD:
                    return 6;
                case NAME:
                    return 1;
                case ALL:
                case PHONE:
                case DEFAULT:
                case AUTO:
                case EMAIL:
                default:
                    return 0;
            }
        }

        private int defaultKeepLast(SensitiveMaskType type) {
            switch (type) {
                case PHONE:
                case DEFAULT:
                    return 4;
                case ID_CARD:
                    return 3;
                case BANK_CARD:
                    return 4;
                case NAME:
                case ALL:
                case AUTO:
                case EMAIL:
                default:
                    return 0;
            }
        }

        private String maskRange(String value, int keepFirst, int keepLast, char maskChar) {
            int length = value.length();
            if (keepFirst + keepLast >= length) {
                return repeat(maskChar, length);
            }
            StringBuilder builder = new StringBuilder(length);
            builder.append(value, 0, keepFirst);
            builder.append(repeat(maskChar, length - keepFirst - keepLast));
            if (keepLast > 0) {
                builder.append(value, length - keepLast, length);
            }
            return builder.toString();
        }

        private String maskEmail(String value, char maskChar) {
            int at = value.indexOf('@');
            if (at <= 0) {
                return maskRange(value, 1, 0, maskChar);
            }
            String local = value.substring(0, at);
            return maskRange(local, 1, 0, maskChar) + value.substring(at);
        }

        private String repeat(char maskChar, int length) {
            StringBuilder builder = new StringBuilder(length);
            for (int index = 0; index < length; index++) {
                builder.append(maskChar);
            }
            return builder.toString();
        }
    }
}
