package io.github.jasper.mybatis.encrypt.core.mask;

import io.github.jasper.mybatis.encrypt.algorithm.AlgorithmRegistry;
import io.github.jasper.mybatis.encrypt.annotation.SensitiveField;
import io.github.jasper.mybatis.encrypt.core.metadata.EncryptColumnRule;
import io.github.jasper.mybatis.encrypt.exception.EncryptionConfigurationException;
import io.github.jasper.mybatis.encrypt.exception.EncryptionErrorCode;
import io.github.jasper.mybatis.encrypt.util.ObjectTraversalUtils;
import io.github.jasper.mybatis.encrypt.util.StringUtils;

import java.lang.reflect.Array;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

/**
 * Applies controller-boundary masking to response objects.
 *
 * <p>This component is deliberately placed after MyBatis result decryption and before HTTP message
 * conversion. It never decides whether a controller is allowed to return sensitive data; that
 * decision is represented by the active {@link SensitiveDataContext}. When masking is required,
 * recorded decrypted references are processed first so the replacement targets the exact DTO
 * instances returned by the controller.</p>
 *
 * <p>Replacement order for recorded values is:</p>
 * <ol>
 *     <li>stored masked values resolved from {@link StoredSensitiveValueResolver};</li>
 *     <li>fallback value generated by the field rule's effective masked algorithm;</li>
 *     <li>{@link SensitiveField} masking on the recorded field, when present.</li>
 * </ol>
 *
 * <p>{@link SensitiveField} supports three annotation-level masking modes. A custom
 * {@link SensitiveFieldMasker} bean has the highest priority, a referenced LIKE algorithm is next,
 * and the built-in type based mask is the default fallback.</p>
 *
 * <p>Graph traversal follows container values and business fields, excluding synthetic links,
 * platform implementation fields and runtime/web infrastructure (including their subclasses).
 * Only classes declaring SensitiveField or selected by SensitiveTraversalPolicy contribute fields.
 * Unknown objects are opaque; third-party wrappers require explicit data adapters.
 * Explicit sensitive-field configuration errors still fail fast.</p>
 *
 * <p>The class is thread-safe. Annotation bindings are cached by response class, while request
 * state is read only from {@link SensitiveDataContext}.</p>
 */
public final class SensitiveDataMasker {

    private final SensitiveTraversalPolicy traversalPolicy;
    private final StoredSensitiveValueResolver storedSensitiveValueResolver;
    private final AlgorithmRegistry algorithmRegistry;
    private final Map<String, SensitiveFieldMasker> sensitiveFieldMaskers;
    private final ConcurrentMap<Class<?>, List<FieldBinding>> fieldBindings =
            new ConcurrentHashMap<Class<?>, List<FieldBinding>>();

    /**
     * Creates a masker without stored-value resolution support.
     *
     * <p>With this constructor, recorded encrypted fields can still be masked by
     * {@code maskedAlgorithm} fallback or by {@link SensitiveField}; database stored masked values
     * are simply skipped.</p>
     */
    public SensitiveDataMasker() {
        this(null, null);
    }

    /**
     * Creates a masker with optional stored-value resolution support.
     *
     * @param storedSensitiveValueResolver stored masked value resolver, may be {@code null}
     * @param algorithmRegistry algorithm registry used for fallback masking
     */
    public SensitiveDataMasker(StoredSensitiveValueResolver storedSensitiveValueResolver,
                               AlgorithmRegistry algorithmRegistry) {
        this(storedSensitiveValueResolver, algorithmRegistry, null);
    }

    /**
     * Creates a masker with optional stored-value, LIKE algorithm and custom field-masker support.
     *
     * @param storedSensitiveValueResolver stored masked value resolver, may be {@code null}
     * @param algorithmRegistry algorithm registry used for fallback masking
     * @param sensitiveFieldMaskers custom response field maskers keyed by bean name
     */
    public SensitiveDataMasker(StoredSensitiveValueResolver storedSensitiveValueResolver,
                               AlgorithmRegistry algorithmRegistry,
                               Map<String, SensitiveFieldMasker> sensitiveFieldMaskers) {
        this(storedSensitiveValueResolver, algorithmRegistry, sensitiveFieldMaskers,
                SensitiveTraversalPolicy.builder().build());
    }

    /**
     * Creates a masker with an explicit DTO traversal boundary. Unknown objects are opaque;
     * recorded references and SensitiveField-declaring classes remain supported by default.
     */
    public SensitiveDataMasker(StoredSensitiveValueResolver storedSensitiveValueResolver,
                               AlgorithmRegistry algorithmRegistry,
                               Map<String, SensitiveFieldMasker> sensitiveFieldMaskers,
                               SensitiveTraversalPolicy traversalPolicy) {
        this.traversalPolicy = java.util.Objects.requireNonNull(traversalPolicy, "traversalPolicy");
        this.storedSensitiveValueResolver = storedSensitiveValueResolver;
        this.algorithmRegistry = algorithmRegistry;
        this.sensitiveFieldMaskers = sensitiveFieldMaskers == null
                ? Collections.<String, SensitiveFieldMasker>emptyMap()
                : Collections.unmodifiableMap(new LinkedHashMap<String, SensitiveFieldMasker>(sensitiveFieldMaskers));
    }

    /**
     * Masks the response object according to the active {@link SensitiveDataContext}.
     *
     * <p>The method mutates the supplied object graph in place and returns the same object
     * reference. If no masking scope is active, the object is returned unchanged.</p>
     *
     * @param body controller response body
     * @return original response body reference
     */
    public Object mask(Object body) {
        if (body == null || !SensitiveDataContext.shouldMask()) {
            return body;
        }
        SensitiveResponseStrategy strategy = SensitiveDataContext.strategy();
        if (strategy == SensitiveResponseStrategy.RECORDED_ONLY
                || strategy == SensitiveResponseStrategy.RECORDED_THEN_ANNOTATED) {
            maskRecordedReferences(body);
        }
        if (strategy == SensitiveResponseStrategy.ANNOTATED_FIELDS
                || strategy == SensitiveResponseStrategy.RECORDED_THEN_ANNOTATED) {
            maskAnnotatedObjectGraph(body);
        }
        return body;
    }

    /**
     * Masks only currently recorded decrypted references.
     *
     * <p>This path is the preferred strategy for normal MyBatis query responses because it avoids
     * traversing the full response graph and replaces only fields that were actually decrypted by
     * the plugin.</p>
     */
    public void maskRecordedReferences() {
        maskRecordedReferences(null);
    }

    private void maskRecordedReferences(Object body) {
        Collection<SensitiveDataContext.SensitiveRecord> records = SensitiveDataContext.records();
        Map<SensitiveDataContext.SensitiveRecord, String> resolvedStoredValues =
                storedSensitiveValueResolver == null
                        ? Collections.<SensitiveDataContext.SensitiveRecord, String>emptyMap()
                        : storedSensitiveValueResolver.resolve(records);
        for (SensitiveDataContext.SensitiveRecord record : records) {
            String replacement = resolveRecordedReplacement(record, resolvedStoredValues);
            if (StringUtils.isBlank(replacement)) {
                continue;
            }
            if (applyRecordedValue(record, replacement)) {
                attachLookupMeta(record);
            }
            applyCopiedRecordedValue(body, record, replacement);
        }
    }

    /**
     * Traverses the explicitly approved DTO graph and masks annotated {@link SensitiveField} String fields.
     *
     * <p>This strategy is intended for manually assembled DTOs that were not recorded by
     * {@link SensitiveDataContext}. Object identity tracking prevents infinite recursion for cyclic
     * graphs.</p>
     *
     * @param body response body
     */
    public void maskAnnotatedObjectGraph(Object body) {
        IdentityHashMap<Object, Boolean> visited = new IdentityHashMap<Object, Boolean>();
        maskObject(body, visited);
    }

    private void maskObject(Object value, IdentityHashMap<Object, Boolean> visited) {
        if (value == null || ObjectTraversalUtils.isSimpleValueType(value.getClass())
                || isInfrastructureType(value.getClass())) {
            return;
        }
        if (visited.put(value, Boolean.TRUE) != null) {
            return;
        }
        Class<?> type = value.getClass();
        java.util.function.Function<Object, Object> adapter = traversalPolicy.adapter(type);
        if (adapter != null) {
            maskObject(adapter.apply(value), visited);
            return;
        }
        if (type.isArray()) {
            int length = Array.getLength(value);
            for (int index = 0; index < length; index++) {
                maskObject(Array.get(value, index), visited);
            }
            return;
        }
        if (value instanceof Iterable<?>) {
            for (Object item : (Iterable<?>) value) {
                maskObject(item, visited);
            }
            return;
        }
        if (value instanceof Map<?, ?>) {
            for (Object item : ((Map<?, ?>) value).values()) {
                maskObject(item, visited);
            }
            return;
        }
        if (isPlatformType(type)) {
            return;
        }
        for (FieldBinding binding : bindings(type)) {
            binding.maskCurrentValue(value, algorithmRegistry, sensitiveFieldMaskers);
        }
        for (Field field : allFields(type)) {
            if (Modifier.isStatic(field.getModifiers()) || field.isSynthetic() || field.getAnnotation(SensitiveField.class) != null) {
                continue;
            }
            if (ObjectTraversalUtils.isSimpleValueType(field.getType())) {
                continue;
            }
            maskObject(SensitiveFieldAccess.read(field, value), visited);
        }
    }

    private Optional<FieldBinding> binding(Class<?> type, String propertyName) {
        for (FieldBinding binding : bindings(type)) {
            if (binding.field.getName().equals(propertyName)) {
                return Optional.of(binding);
            }
        }
        return Optional.empty();
    }

    private boolean applyRecordedValue(SensitiveDataContext.SensitiveRecord record, String replacement) {
        if (StringUtils.isBlank(replacement)) {
            return false;
        }
        Object owner = record.owner();
        String[] path = record.propertyName().split("\\.");
        for (int index = 0; index < path.length; index++) {
            if (owner == null) return false;
            boolean last = index == path.length - 1;
            if (owner instanceof Map<?, ?>) {
                @SuppressWarnings("unchecked")
                Map<Object, Object> map = (Map<Object, Object>) owner;
                if (last) {
                    Object value = map.get(path[index]);
                    if (value != null && !(value instanceof String)) return false;
                    map.put(path[index], replacement);
                    return true;
                }
                owner = map.get(path[index]);
            } else {
                Field field = recordedField(owner.getClass(), path[index]);
                Object value = SensitiveFieldAccess.read(field, owner);
                if (last) {
                    if (value != null && !(value instanceof String)) return false;
                    SensitiveFieldAccess.write(field, owner, replacement);
                    return true;
                }
                owner = value;
            }
        }
        return false;
    }

    // A decrypted record explicitly authorizes this property, not arbitrary sibling traversal.
    private Field recordedField(Class<?> type, String name) {
        for (Class<?> current = type; current != null && !isPlatformType(current)
                && !isInfrastructureType(current); current = current.getSuperclass()) {
            try {
                Field field = current.getDeclaredField(name);
                if (!Modifier.isStatic(field.getModifiers()) && !field.isSynthetic()) return field;
                break;
            } catch (NoSuchFieldException ignored) {
                // Follow business inheritance for this exact recorded property only.
            }
        }
        throw new EncryptionConfigurationException(EncryptionErrorCode.INVALID_FIELD_RULE,
                "Cannot resolve recorded sensitive response field: " + type.getName() + "." + name);
    }

    private String resolveRecordedReplacement(SensitiveDataContext.SensitiveRecord record,
                                              Map<SensitiveDataContext.SensitiveRecord, String> resolvedStoredValues) {
        String storedMaskedValue = resolvedStoredValues.get(record);
        if (StringUtils.isNotBlank(storedMaskedValue)) {
            return storedMaskedValue;
        }
        EncryptColumnRule rule = record.rule();
        if (rule != null && rule.hasMaskedColumn() && algorithmRegistry != null) {
            return algorithmRegistry.like(rule.effectiveMaskedAlgorithm()).transform(record.value());
        }
        FieldBinding binding = binding(record.owner().getClass(), record.propertyName()).orElse(null);
        return binding == null
                ? null
                : binding.mask(record.owner(), record.value(), algorithmRegistry, sensitiveFieldMaskers);
    }

    private boolean applyCopiedRecordedValue(Object body,
                                             SensitiveDataContext.SensitiveRecord record,
                                             String replacement) {
        if (body == null || record == null || StringUtils.isBlank(replacement)) {
            return false;
        }
        IdentityHashMap<Object, Boolean> visited = new IdentityHashMap<Object, Boolean>();
        return applyCopiedRecordedValue(body, record, replacement, visited);
    }

    private boolean applyCopiedRecordedValue(Object value,
                                             SensitiveDataContext.SensitiveRecord record,
                                             String replacement,
                                             IdentityHashMap<Object, Boolean> visited) {
        if (value == null || ObjectTraversalUtils.isSimpleValueType(value.getClass())
                || isInfrastructureType(value.getClass())) {
            return false;
        }
        if (visited.put(value, Boolean.TRUE) != null) {
            return false;
        }
        Class<?> type = value.getClass();
        java.util.function.Function<Object, Object> adapter = traversalPolicy.adapter(type);
        if (adapter != null) {
            return applyCopiedRecordedValue(adapter.apply(value), record, replacement, visited);
        }
        if (type.isArray()) {
            boolean changed = false;
            int length = Array.getLength(value);
            for (int index = 0; index < length; index++) {
                changed |= applyCopiedRecordedValue(Array.get(value, index), record, replacement, visited);
            }
            return changed;
        }
        if (value instanceof Iterable<?>) {
            boolean changed = false;
            for (Object item : (Iterable<?>) value) {
                changed |= applyCopiedRecordedValue(item, record, replacement, visited);
            }
            return changed;
        }
        if (value instanceof Map<?, ?>) {
            return applyCopiedMapRecordedValue((Map<?, ?>) value, record, replacement, visited);
        }
        if (isPlatformType(type)) {
            return false;
        }
        return applyCopiedObjectRecordedValue(value, record, replacement, visited);
    }

    private boolean applyCopiedMapRecordedValue(Map<?, ?> map,
                                                SensitiveDataContext.SensitiveRecord record,
                                                String replacement,
                                                IdentityHashMap<Object, Boolean> visited) {
        boolean changed = false;
        boolean shouldAttachLookupMeta = false;
        for (Map.Entry<?, ?> entry : map.entrySet()) {
            Object key = entry.getKey();
            Object value = entry.getValue();
            if (record.propertyName().equals(key) && record.value().equals(value)) {
                @SuppressWarnings("unchecked")
                Map<Object, Object> writable = (Map<Object, Object>) map;
                writable.put(key, replacement);
                shouldAttachLookupMeta = true;
                changed = true;
                continue;
            }
            changed |= applyCopiedRecordedValue(value, record, replacement, visited);
        }
        if (shouldAttachLookupMeta) {
            @SuppressWarnings("unchecked")
            Map<Object, Object> writable = (Map<Object, Object>) map;
            attachLookupMetaToCopiedMap(writable, record);
        }
        return changed;
    }

    private boolean applyCopiedObjectRecordedValue(Object owner,
                                                   SensitiveDataContext.SensitiveRecord record,
                                                   String replacement,
                                                   IdentityHashMap<Object, Boolean> visited) {
        boolean changed = false;
        for (Field field : allFields(owner.getClass())) {
            if (Modifier.isStatic(field.getModifiers()) || field.isSynthetic()) {
                continue;
            }
            boolean candidate = field.getName().equals(record.propertyName())
                    && String.class.equals(field.getType());
            if (!candidate && ObjectTraversalUtils.isSimpleValueType(field.getType())) continue;
            Object fieldValue = SensitiveFieldAccess.read(field, owner);
            if (candidate && record.value().equals(fieldValue)) {
                SensitiveFieldAccess.write(field, owner, replacement);
                attachLookupMetaToCopiedOwner(owner, record);
                changed = true;
                continue;
            }
            changed |= applyCopiedRecordedValue(fieldValue, record, replacement, visited);
        }
        return changed;
    }

    private void attachLookupMeta(SensitiveDataContext.SensitiveRecord record) {
        if (record == null || record.lookupMeta() == null) {
            return;
        }
        if (!(record.owner() instanceof SensitiveExtraInfoSupport)) {
            return;
        }
        FieldBinding binding = binding(record.owner().getClass(), record.propertyName()).orElse(null);
        if (binding != null && !binding.shouldReturnLookupMeta()) {
            return;
        }
        ((SensitiveExtraInfoSupport) record.owner()).sensitiveLookupMetaStorage()
                .put(record.propertyName(), record.lookupMeta());
    }

    private void attachLookupMetaToCopiedOwner(Object owner, SensitiveDataContext.SensitiveRecord record) {
        if (owner instanceof SensitiveExtraInfoSupport) {
            ((SensitiveExtraInfoSupport) owner).sensitiveLookupMetaStorage()
                    .put(record.propertyName(), record.lookupMeta());
        }
    }

    private void attachLookupMetaToCopiedMap(Map<Object, Object> map, SensitiveDataContext.SensitiveRecord record) {
        if (record.lookupMeta() == null) {
            return;
        }
        Object existing = map.get("sensitiveLookupMeta");
        Map<String, SensitiveDataContext.SensitiveLookupMeta> metaByProperty;
        if (existing instanceof Map<?, ?>) {
            @SuppressWarnings("unchecked")
            Map<String, SensitiveDataContext.SensitiveLookupMeta> cast =
                    (Map<String, SensitiveDataContext.SensitiveLookupMeta>) existing;
            metaByProperty = cast;
        } else {
            metaByProperty = new LinkedHashMap<String, SensitiveDataContext.SensitiveLookupMeta>();
            map.put("sensitiveLookupMeta", metaByProperty);
        }
        metaByProperty.put(record.propertyName(), record.lookupMeta());
    }

    private List<FieldBinding> bindings(Class<?> type) {
        List<FieldBinding> cached = fieldBindings.get(type);
        if (cached != null) {
            return cached;
        }
        List<FieldBinding> resolved = resolveBindings(type);
        List<FieldBinding> previous = fieldBindings.putIfAbsent(type, resolved);
        return previous == null ? resolved : previous;
    }

    private List<FieldBinding> resolveBindings(Class<?> type) {
        List<FieldBinding> bindings = new ArrayList<FieldBinding>();
        for (Field field : allFields(type)) {
            SensitiveField annotation = field.getAnnotation(SensitiveField.class);
            if (annotation == null) {
                continue;
            }
            if (!String.class.equals(field.getType())) {
                throw new EncryptionConfigurationException(EncryptionErrorCode.INVALID_FIELD_RULE,
                        "@SensitiveField can only be used on String fields: "
                                + field.getDeclaringClass().getName() + "." + field.getName());
            }
            if (Modifier.isStatic(field.getModifiers()) || Modifier.isFinal(field.getModifiers())) {
                throw new EncryptionConfigurationException(EncryptionErrorCode.INVALID_FIELD_RULE,
                        "@SensitiveField cannot be used on static or final fields: "
                                + field.getDeclaringClass().getName() + "." + field.getName());
            }
            bindings.add(new FieldBinding(field, annotation, parseOptions(annotation, field)));
        }
        return Collections.unmodifiableList(bindings);
    }

    private Map<String, String> parseOptions(SensitiveField annotation, Field field) {
        String[] options = annotation.options();
        if (options == null || options.length == 0) {
            return Collections.emptyMap();
        }
        Map<String, String> parsed = new LinkedHashMap<String, String>();
        for (String option : options) {
            if (StringUtils.isBlank(option)) {
                continue;
            }
            int splitIndex = option.indexOf('=');
            if (splitIndex <= 0) {
                throw new EncryptionConfigurationException(EncryptionErrorCode.INVALID_FIELD_RULE,
                        "@SensitiveField options must use key=value: "
                                + field.getDeclaringClass().getName() + "." + field.getName()
                                + ", option=" + option);
            }
            String key = option.substring(0, splitIndex).trim();
            if (StringUtils.isBlank(key)) {
                throw new EncryptionConfigurationException(EncryptionErrorCode.INVALID_FIELD_RULE,
                        "@SensitiveField option key must not be blank: "
                                + field.getDeclaringClass().getName() + "." + field.getName()
                                + ", option=" + option);
            }
            if (parsed.containsKey(key)) {
                throw new EncryptionConfigurationException(EncryptionErrorCode.INVALID_FIELD_RULE,
                        "@SensitiveField option key is duplicated: "
                                + field.getDeclaringClass().getName() + "." + field.getName()
                                + ", key=" + key);
            }
            parsed.put(key, option.substring(splitIndex + 1).trim());
        }
        return Collections.unmodifiableMap(parsed);
    }

    // Containers are traversed through their public APIs, never through JDK implementation fields.
    private static boolean isPlatformType(Class<?> type) {
        // JDK APIs also use org.xml.sax/org.w3c.dom and other non-java package names.
        // Detect bootstrap and platform/extension loader ownership using Java 8 APIs.
        // Check each declaring class separately so application subclasses retain business fields.
        ClassLoader definingLoader = type.getClassLoader();
        if (definingLoader == null) {
            return true;
        }
        ClassLoader systemLoader = ClassLoader.getSystemClassLoader();
        for (ClassLoader platformLoader = systemLoader == null ? null : systemLoader.getParent();
             platformLoader != null; platformLoader = platformLoader.getParent()) {
            if (definingLoader == platformLoader) {
                return true;
            }
        }
        String name = type.getName();
        return name.startsWith("java.") || name.startsWith("javax.")
                || name.startsWith("jakarta.") || name.startsWith("jdk.")
                || name.startsWith("sun.") || name.startsWith("com.sun.");
    }

    // Check assignability, not just the concrete package: application/container class loaders
    // inherit inaccessible JDK fields. Named framework contracts keep common dependency-free.
    private static boolean isInfrastructureType(Class<?> type) {
        if (type == null) {
            return false;
        }
        if (ClassLoader.class.isAssignableFrom(type) || Thread.class.isAssignableFrom(type)
                || java.lang.reflect.Member.class.isAssignableFrom(type)
                || java.lang.reflect.AccessibleObject.class.isAssignableFrom(type)) {
            return true;
        }
        String name = type.getName();
        if (name.equals("org.springframework.validation.BindingResult")
                || name.equals("org.springframework.beans.factory.BeanFactory")
                || name.equals("org.springframework.web.servlet.support.RequestContext")
                || name.equals("javax.servlet.ServletRequest")
                || name.equals("jakarta.servlet.ServletRequest")
                || name.equals("javax.servlet.ServletResponse")
                || name.equals("jakarta.servlet.ServletResponse")
                || name.equals("javax.servlet.ServletContext")
                || name.equals("jakarta.servlet.ServletContext")
                || name.equals("javax.servlet.http.HttpSession")
                || name.equals("jakarta.servlet.http.HttpSession")) {
            return true;
        }
        for (Class<?> contract : type.getInterfaces()) {
            if (isInfrastructureType(contract)) {
                return true;
            }
        }
        return isInfrastructureType(type.getSuperclass());
    }

    private List<Field> allFields(Class<?> type) {
        if (type == null || type == Object.class) {
            return Collections.emptyList();
        }
        List<Field> fields = new ArrayList<Field>();
        Class<?> current = type;
        while (current != null && current != Object.class && !isPlatformType(current)
                && !isInfrastructureType(current)) {
            // Authorize each declaring class, not the whole hierarchy. A DTO subclass cannot
            // grant reflection access to an unrelated library superclass.
            Field[] declared = current.getDeclaredFields();
            boolean selected = traversalPolicy.allows(current);
            if (!selected) {
                for (Field field : declared) {
                    if (field.getAnnotation(SensitiveField.class) != null) {
                        selected = true;
                        break;
                    }
                }
            }
            if (selected) Collections.addAll(fields, declared);
            current = current.getSuperclass();
        }
        return fields;
    }

    private static final class FieldBinding {

        private final Field field;
        private final SensitiveField annotation;
        private final Map<String, String> options;

        private FieldBinding(Field field, SensitiveField annotation, Map<String, String> options) {
            this.field = field;
            this.annotation = annotation;
            this.options = options;
        }

        private void maskCurrentValue(Object owner,
                                      AlgorithmRegistry algorithmRegistry,
                                      Map<String, SensitiveFieldMasker> sensitiveFieldMaskers) {
            Object value = SensitiveFieldAccess.read(field, owner);
            if (value instanceof String) {
                SensitiveFieldAccess.write(field, owner,
                        mask(owner, (String) value, algorithmRegistry, sensitiveFieldMaskers));
            }
        }

        private String mask(Object owner,
                            String value,
                            AlgorithmRegistry algorithmRegistry,
                            Map<String, SensitiveFieldMasker> sensitiveFieldMaskers) {
            if (StringUtils.isBlank(value)) {
                return value;
            }
            if (StringUtils.isNotBlank(annotation.masker())) {
                SensitiveFieldMasker masker = sensitiveFieldMaskers.get(annotation.masker());
                if (masker == null) {
                    throw new EncryptionConfigurationException(EncryptionErrorCode.MISSING_SENSITIVE_FIELD_MASKER,
                            "Missing sensitive field masker bean: " + annotation.masker()
                                    + " for " + field.getDeclaringClass().getName() + "." + field.getName());
                }
                String masked = masker.mask(value, new SensitiveFieldMaskingContext(
                        owner, field.getDeclaringClass(), field.getName(), annotation, options));
                return masked == null ? value : masked;
            }
            if (StringUtils.isNotBlank(annotation.likeAlgorithm())) {
                if (algorithmRegistry == null) {
                    throw new EncryptionConfigurationException(EncryptionErrorCode.MISSING_LIKE_QUERY_ALGORITHM,
                            "Missing AlgorithmRegistry for @SensitiveField likeAlgorithm: "
                                    + annotation.likeAlgorithm() + " on "
                                    + field.getDeclaringClass().getName() + "." + field.getName());
                }
                return algorithmRegistry.like(annotation.likeAlgorithm()).transform(value);
            }
            SensitiveMaskType type = resolveType();
            if (type == SensitiveMaskType.EMAIL) {
                return maskEmail(value, annotation.maskChar());
            }
            int keepFirst = annotation.keepFirst() >= 0 ? annotation.keepFirst() : defaultKeepFirst(type);
            int keepLast = annotation.keepLast() >= 0 ? annotation.keepLast() : defaultKeepLast(type);
            return maskRange(value, keepFirst, keepLast, annotation.maskChar());
        }

        private SensitiveMaskType resolveType() {
            if (annotation.type() != SensitiveMaskType.AUTO) {
                return annotation.type();
            }
            String name = field.getName().toLowerCase(Locale.ROOT);
            if (name.contains("phone") || name.contains("mobile") || name.contains("tel")) {
                return SensitiveMaskType.PHONE;
            }
            if (name.contains("idcard") || name.contains("id_card") || name.contains("credential")
                    || name.contains("cert")) {
                return SensitiveMaskType.ID_CARD;
            }
            if (name.contains("bank") || name.contains("card")) {
                return SensitiveMaskType.BANK_CARD;
            }
            if (name.contains("email") || name.contains("mail")) {
                return SensitiveMaskType.EMAIL;
            }
            if (name.contains("name")) {
                return SensitiveMaskType.NAME;
            }
            return SensitiveMaskType.DEFAULT;
        }

        private int defaultKeepFirst(SensitiveMaskType type) {
            switch (type) {
                case ID_CARD:
                    return 3;
                case BANK_CARD:
                    return 6;
                case NAME:
                    return 1;
                case ALL:
                case PHONE:
                case DEFAULT:
                case AUTO:
                case EMAIL:
                default:
                    return 0;
            }
        }

        private int defaultKeepLast(SensitiveMaskType type) {
            switch (type) {
                case PHONE:
                case DEFAULT:
                    return 4;
                case ID_CARD:
                    return 3;
                case BANK_CARD:
                    return 4;
                case NAME:
                case ALL:
                case AUTO:
                case EMAIL:
                default:
                    return 0;
            }
        }

        private String maskRange(String value, int keepFirst, int keepLast, char maskChar) {
            int length = value.length();
            if (keepFirst + keepLast >= length) {
                return repeat(maskChar, length);
            }
            StringBuilder builder = new StringBuilder(length);
            builder.append(value, 0, keepFirst);
            builder.append(repeat(maskChar, length - keepFirst - keepLast));
            if (keepLast > 0) {
                builder.append(value, length - keepLast, length);
            }
            return builder.toString();
        }

        private String maskEmail(String value, char maskChar) {
            int at = value.indexOf('@');
            if (at <= 0) {
                return maskRange(value, 1, 0, maskChar);
            }
            String local = value.substring(0, at);
            return maskRange(local, 1, 0, maskChar) + value.substring(at);
        }

        private String repeat(char maskChar, int length) {
            StringBuilder builder = new StringBuilder(length);
            for (int index = 0; index < length; index++) {
                builder.append(maskChar);
            }
            return builder.toString();
        }

        private boolean shouldReturnLookupMeta() {
            return annotation.returnLookupMeta();
        }
    }
}
