package io.github.jasper.mybatis.encrypt.migration;

/**
 * Structured error codes for migration planning, execution and resume flows.
 */
public enum MigrationErrorCode {

    GENERAL_FAILURE,
    DEFINITION_INVALID,
    METADATA_RULE_MISSING,
    FIELD_SELECTOR_UNRESOLVED,
    BACKUP_COLUMN_CONFLICT,
    CURSOR_VALUE_MISSING,
    CURSOR_CHECKPOINT_INVALID,
    RANGE_READ_FAILED,
    EXECUTION_FAILED,
    CONFIRMATION_REQUIRED,
    CONFIRMATION_SCOPE_MISMATCH,
    CONFIRMATION_IO_FAILED,
    STATE_STORE_IO_FAILED,
    STATE_STORE_DATA_INVALID,
    VERIFICATION_REFERENCE_MISSING,
    VERIFICATION_MAIN_ROW_MISSING,
    VERIFICATION_EXTERNAL_ROW_MISSING,
    VERIFICATION_VALUE_MISMATCH
}
