package io.github.jasper.mybatis.encrypt.exception;

/**
 * Structured runtime error codes for encryption configuration and SQL processing.
 */
public enum EncryptionErrorCode {

    GENERAL_FAILURE,
    MISSING_CIPHER_ALGORITHM,
    MISSING_ASSISTED_QUERY_ALGORITHM,
    MISSING_LIKE_QUERY_ALGORITHM,
    INVALID_TABLE_RULE,
    INVALID_FIELD_RULE,
    MISSING_STORAGE_TABLE,
    MISSING_ASSISTED_QUERY_COLUMN,
    MISSING_LIKE_QUERY_COLUMN,
    CIPHER_OPERATION_FAILED,
    ASSISTED_QUERY_OPERATION_FAILED,
    SEPARATE_TABLE_OPERATION_FAILED,
    SQL_REWRITE_FAILED,
    AMBIGUOUS_ENCRYPTED_REFERENCE,
    INVALID_ENCRYPTED_QUERY_OPERAND,
    INVALID_ENCRYPTED_WRITE_OPERAND,
    UNSUPPORTED_ENCRYPTED_INSERT,
    UNSUPPORTED_ENCRYPTED_SELECT,
    UNSUPPORTED_ENCRYPTED_IN_QUERY,
    UNSUPPORTED_ENCRYPTED_RANGE,
    UNSUPPORTED_ENCRYPTED_ORDER_BY,
    UNSUPPORTED_ENCRYPTED_DISTINCT,
    UNSUPPORTED_ENCRYPTED_AGGREGATION,
    UNSUPPORTED_ENCRYPTED_WINDOW,
    UNSUPPORTED_ENCRYPTED_GROUP_BY,
    UNSUPPORTED_ENCRYPTED_OPERATION
}
